version: '3.1'

services:
  gateway:
    #image: TODO
    build:
      context: './${USER_OFFICE_GATEWAY_DIR}'
    env_file:
      - .env
    environment:
      USER_OFFICE_BACKEND: '${USER_OFFICE_BACKEND}'
      USER_OFFICE_SCHEDULER_BACKEND: ${USER_OFFICE_SCHEDULER_BACKEND}
      NODE_ENV: development
    labels:
      - 'traefik.frontend.rule=PathPrefix:/gateway'
      - 'traefik.port=4100'
