version: "3.1"

services:
  gateway:
    image: "dmsc/duo-gateway:${USER_OFFICE_GATEWAY_TAG}"
    environment:
      USER_OFFICE_BACKEND: "${USER_OFFICE_BACKEND}"
      USER_OFFICE_SCHEDULER_BACKEND: ${USER_OFFICE_SCHEDULER_BACKEND}
      NODE_ENV: production
    labels:
      - "traefik.frontend.rule=PathPrefix:/gateway, /graphql"
      - "traefik.port=4100"
