ARG WINDOWS_VERSION
FROM dmsc/bisapps-node:12-servercore${WINDOWS_VERSION} as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm ci --loglevel error --no-fund

COPY . .

RUN  npx tsc


FROM dmsc/bisapps-node:12-servercore${WINDOWS_VERSION}

WORKDIR /app

COPY --from=build-stage /app/build ./build
COPY --from=build-stage /app/package.json /app/package-lock.json ./

RUN npm ci --only=production --loglevel error --no-fund

EXPOSE 4100

CMD [ "node", "./build/index.js" ]
