name: Build, Test and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [develop, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: 18.x-cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - run: npm ci --loglevel error --no-fund
      - run: npm run build
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache app docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-layer-cache
          key: ${{ runner.os }}-buildx-${{ github.head_ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.head_ref }}-
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        # Don't login if dependabot is creating the PR
        if: ${{ !startsWith(github.head_ref, 'dependabot') }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # For debugging capture the selected branch
      - name: Extracted branch
        run: echo "Extracted branch ${{ github.head_ref }}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ !startsWith(github.head_ref, 'dependabot') }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/userofficeproject/user-office-gateway:${{ github.head_ref }}
          cache-from: type=local,src=/tmp/.buildx-layer-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-layer-cache
